export const destinations = [
  {
    id: 'd1',
    name: 'Bali, Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800',
    tours: 12,
  },
  {
    id: 'd2',
    name: 'Santorini, Greece',
    image: 'https://images.unsplash.com/photo-1515859005217-8a1f08870f59?auto=format&fit=crop&q=80&w=800',
    tours: 8,
  },
  {
    id: 'd3',
    name: 'Kyoto, Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800',
    tours: 15,
  },
  {
    id: 'd4',
    name: 'Swiss Alps',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&q=80&w=800',
    tours: 6,
  },
  {
    id: 'd5',
    name: 'Machu Picchu, Peru',
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&q=80&w=800',
    tours: 5,
  },
  {
    id: 'd6',
    name: 'Banff, Canada',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&q=80&w=800',
    tours: 9,
  },
  {
    id: 'd7',
    name: 'Amalfi Coast, Italy',
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800',
    tours: 11,
  },
  {
    id: 'd8',
    name: 'Phuket, Thailand',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&q=80&w=800',
    tours: 14,
  },
];

export const packages = [
  {
    id: 'p1',
    title: 'Tropical Paradise Escape',
    location: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=800',
    price: 1299,
    originalPrice: 1599,
    days: 7,
    rating: 4.9,
    reviews: 124,
    description: 'Experience the ultimate luxury in overwater bungalows with crystal clear waters and vibrant marine life.',
    itinerary: [
      { day: 1, title: 'Arrival & Welcome', description: 'Speedboat transfer to resort, welcome drinks, and leisure time.' },
      { day: 2, title: 'Snorkeling Adventure', description: 'Guided snorkeling tour of the house reef.' },
      { day: 3, title: 'Spa & Relaxation', description: 'Full day access to the premium spa facilities.' },
      { day: 4, title: 'Sunset Cruise', description: 'Romantic sunset cruise with dolphin watching.' },
      { day: 5, title: 'Local Island Visit', description: 'Cultural tour to a nearby inhabited island.' },
      { day: 6, title: 'Free Day', description: 'Enjoy the resort amenities at your own pace.' },
      { day: 7, title: 'Departure', description: 'Transfer back to the airport.' },
    ],
    hotel: {
      name: 'Azure Water Resort & Spa',
      rating: 5,
      amenities: ['Free WiFi', 'Infinity Pool', 'Spa', 'Private Beach', 'All-Inclusive'],
    },
    inclusions: ['Round-trip flights', '6 nights accommodation', 'All meals and selected drinks', 'Airport transfers', 'Snorkeling gear'],
    exclusions: ['Travel insurance', 'Personal expenses', 'Premium alcoholic beverages'],
  },
  {
    id: 'p2',
    title: 'European Cultural Tour',
    location: 'Paris, Rome, Barcelona',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&q=80&w=800',
    price: 2499,
    originalPrice: 2899,
    days: 14,
    rating: 4.8,
    reviews: 89,
    description: 'A comprehensive journey through three of Europe\'s most iconic cities, filled with history, art, and culinary delights.',
    itinerary: [
      { day: 1, title: 'Arrival in Paris', description: 'Check-in and welcome dinner near the Eiffel Tower.' },
      { day: 2, title: 'Louvre & Seine', description: 'Morning museum tour, evening river cruise.' },
      { day: 3, title: 'Versailles', description: 'Half-day trip to the Palace of Versailles.' },
      { day: 4, title: 'Train to Rome', description: 'Scenic train ride through the Alps.' },
      { day: 5, title: 'Ancient Rome', description: 'Colosseum and Roman Forum guided tour.' },
      { day: 6, title: 'Vatican City', description: 'St. Peter\'s Basilica and Sistine Chapel.' },
      { day: 7, title: 'Flight to Barcelona', description: 'Afternoon arrival and tapas tour.' },
      { day: 8, title: 'Gaudí Architecture', description: 'Sagrada Familia and Park Güell.' },
      { day: 9, title: 'Gothic Quarter', description: 'Walking tour and free afternoon.' },
      { day: 10, title: 'Departure', description: 'Transfer to Barcelona airport.' },
    ],
    hotel: {
      name: 'Various 4-Star Hotels',
      rating: 4,
      amenities: ['Free WiFi', 'Central Location', 'Breakfast Included', 'Air Conditioning'],
    },
    inclusions: ['Inter-city transport (train/flight)', '9 nights accommodation', 'Daily breakfast', 'Guided tours', 'Museum passes'],
    exclusions: ['International flights', 'Lunches and dinners', 'City taxes'],
  },
  {
    id: 'p3',
    title: 'Safari Adventure',
    location: 'Serengeti, Tanzania',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=800',
    price: 3199,
    originalPrice: null,
    days: 8,
    rating: 5.0,
    reviews: 56,
    description: 'Witness the Great Migration and spot the Big Five in their natural habitat on this unforgettable African safari.',
    itinerary: [
      { day: 1, title: 'Arrival in Arusha', description: 'Transfer to lodge and safari briefing.' },
      { day: 2, title: 'Tarangire National Park', description: 'First game drive, known for elephant herds.' },
      { day: 3, title: 'Ngorongoro Crater', description: 'Descend into the crater for diverse wildlife viewing.' },
      { day: 4, title: 'Enter the Serengeti', description: 'Drive to Serengeti with game viewing en route.' },
      { day: 5, title: 'Full Day Serengeti', description: 'Morning and afternoon game drives.' },
      { day: 6, title: 'Following the Herds', description: 'Tracking the migration patterns.' },
      { day: 7, title: 'Hot Air Balloon Safari', description: 'Optional sunrise balloon ride (extra cost).' },
      { day: 8, title: 'Departure', description: 'Fly back to Arusha for onward journey.' },
    ],
    hotel: {
      name: 'Luxury Tented Camps',
      rating: 5,
      amenities: ['En-suite bathrooms', 'Campfires', 'Full Board', 'Expert Guides'],
    },
    inclusions: ['4x4 Safari vehicle', '7 nights accommodation', 'All meals on safari', 'Park fees', 'English-speaking guide'],
    exclusions: ['International flights', 'Visas', 'Tips and gratuities'],
  },
  {
    id: 'p4',
    title: 'Mystical Machu Picchu',
    location: 'Cusco, Peru',
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&q=80&w=800',
    price: 1899,
    originalPrice: 2100,
    days: 7,
    rating: 4.7,
    reviews: 92,
    description: 'Trek the ancient Inca Trail and discover the breathtaking ruins of Machu Picchu nestled high in the Andes.',
    itinerary: [
      { day: 1, title: 'Arrival in Cusco', description: 'Acclimatization and city tour.' },
      { day: 2, title: 'Sacred Valley', description: 'Visit Pisac market and Ollantaytambo.' },
      { day: 3, title: 'Inca Trail Day 1', description: 'Start the trek from km 82.' },
      { day: 4, title: 'Inca Trail Day 2', description: 'Cross Dead Woman\'s Pass.' },
      { day: 5, title: 'Inca Trail Day 3', description: 'Descend into the cloud forest.' },
      { day: 6, title: 'Machu Picchu', description: 'Arrive at the Sun Gate at dawn.' },
      { day: 7, title: 'Departure', description: 'Train back to Cusco and fly home.' },
    ],
    hotel: {
      name: 'Andean Boutique Hotel & Camps',
      rating: 4,
      amenities: ['Free WiFi in hotel', 'Camping Gear', 'Porters', 'Dining Tent'],
    },
    inclusions: ['Inca Trail permits', 'Guided trek', 'Camping equipment', 'Meals during trek', 'Train tickets'],
    exclusions: ['International flights', 'Sleeping bags', 'Gratuities'],
  },
  {
    id: 'p5',
    title: 'Northern Lights Expedition',
    location: 'Tromsø, Norway',
    image: 'https://images.unsplash.com/photo-1520769945061-0a448c463865?auto=format&fit=crop&q=80&w=800',
    price: 2199,
    originalPrice: null,
    days: 5,
    rating: 4.9,
    reviews: 78,
    description: 'Chase the Aurora Borealis across the Arctic Circle with dog sledding and snowmobile adventures.',
    itinerary: [
      { day: 1, title: 'Arrival in Tromsø', description: 'Check-in and evening Aurora hunt.' },
      { day: 2, title: 'Husky Safari', description: 'Drive your own team of huskies.' },
      { day: 3, title: 'Snowmobile Tour', description: 'Explore the Lyngen Alps by snowmobile.' },
      { day: 4, title: 'Sami Culture', description: 'Reindeer sledding and traditional Sami meal.' },
      { day: 5, title: 'Departure', description: 'Morning at leisure and airport transfer.' },
    ],
    hotel: {
      name: 'Arctic Ice Hotel',
      rating: 4,
      amenities: ['Thermal Suits', 'Sauna', 'Breakfast Included', 'Aurora Wake-up Call'],
    },
    inclusions: ['Winter clothing rental', '4 nights accommodation', 'Guided tours', 'Breakfasts'],
    exclusions: ['Flights', 'Lunches and dinners', 'Optional excursions'],
  },
  {
    id: 'p6',
    title: 'Island Hopping in Greece',
    location: 'Athens, Mykonos, Santorini',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&q=80&w=800',
    price: 1999,
    originalPrice: 2299,
    days: 10,
    rating: 4.8,
    reviews: 156,
    description: 'Experience the perfect blend of ancient history in Athens and the stunning beaches of the Cyclades.',
    itinerary: [
      { day: 1, title: 'Arrival in Athens', description: 'Welcome dinner in Plaka.' },
      { day: 2, title: 'Acropolis Tour', description: 'Guided tour of the Parthenon and museum.' },
      { day: 3, title: 'Ferry to Mykonos', description: 'High-speed ferry and beach afternoon.' },
      { day: 4, title: 'Mykonos Town', description: 'Explore the windmills and Little Venice.' },
      { day: 5, title: 'Delos Excursion', description: 'Half-day trip to the sacred island of Delos.' },
      { day: 6, title: 'Ferry to Santorini', description: 'Arrive and check into caldera-view hotel.' },
      { day: 7, title: 'Volcano Cruise', description: 'Sail to the volcanic islands and hot springs.' },
      { day: 8, title: 'Oia Sunset', description: 'Wine tasting and famous sunset viewing.' },
      { day: 9, title: 'Free Day', description: 'Relax on the black sand beaches.' },
      { day: 10, title: 'Departure', description: 'Fly back to Athens for onward journey.' },
    ],
    hotel: {
      name: 'Premium Boutique Hotels',
      rating: 4,
      amenities: ['Sea Views', 'Pool', 'Breakfast Included', 'Free WiFi'],
    },
    inclusions: ['Ferry tickets', '9 nights accommodation', 'Daily breakfast', 'Guided tours'],
    exclusions: ['International flights', 'Lunches and dinners', 'Port taxes'],
  }
];

export const testimonials = [
  {
    id: 't1',
    name: 'Sarah Jenkins',
    role: 'Adventure Traveler',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    text: 'Global B organized the most incredible trip to Japan for my family. Every detail was perfect, from the bullet train tickets to the ryokan stays. Highly recommend!',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Michael Chen',
    role: 'Honeymooner',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    text: 'Our Maldives honeymoon was a dream come true. The booking process was seamless, and the resort recommendation was spot on. Thank you for the memories!',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Emma Thompson',
    role: 'Solo Explorer',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=200',
    text: 'As a solo female traveler, safety is my top priority. Global B ensured I felt secure and well-guided throughout my European tour while still giving me freedom to explore.',
    rating: 4,
  },
];

export const offers = [
  {
    id: 'o1',
    title: 'Early Bird Summer 2026',
    discount: '20% OFF',
    description: 'Book your summer vacation now and save big on all European destinations.',
    code: 'SUMMER26',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'o2',
    title: 'Honeymoon Special',
    discount: 'Free Upgrade',
    description: 'Get a complimentary room upgrade and romantic dinner on all island packages.',
    code: 'ROMANCE',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800'
  }
];
